#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-aggdesigner
Version  : 6.0
Release  : 2
URL      : https://github.com/julianhyde/aggdesigner/archive/aggdesigner-6.0.tar.gz
Source0  : https://github.com/julianhyde/aggdesigner/archive/aggdesigner-6.0.tar.gz
Source1  : https://repo.maven.apache.org/maven2/net/hydromatic/aggdesigner-algorithm/6.0/aggdesigner-algorithm-6.0.jar
Source2  : https://repo.maven.apache.org/maven2/net/hydromatic/aggdesigner-algorithm/6.0/aggdesigner-algorithm-6.0.pom
Source3  : https://repo.maven.apache.org/maven2/net/hydromatic/aggdesigner/6.0/aggdesigner-6.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-aggdesigner-data = %{version}-%{release}
Requires: mvn-aggdesigner-license = %{version}-%{release}
BuildRequires : apache-ant
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
This directory contains scripts for use in development only.

%package data
Summary: data components for the mvn-aggdesigner package.
Group: Data

%description data
data components for the mvn-aggdesigner package.


%package license
Summary: license components for the mvn-aggdesigner package.
Group: Default

%description license
license components for the mvn-aggdesigner package.


%prep
%setup -q -n aggdesigner-aggdesigner-6.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-aggdesigner
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-aggdesigner/LICENSE
cp NOTICE %{buildroot}/usr/share/package-licenses/mvn-aggdesigner/NOTICE
cp pentaho-aggdesigner-algorithm/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-aggdesigner/pentaho-aggdesigner-algorithm_LICENSE.txt
cp pentaho-aggdesigner-core/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-aggdesigner/pentaho-aggdesigner-core_LICENSE.txt
cp pentaho-aggdesigner-ui/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-aggdesigner/pentaho-aggdesigner-ui_LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/hydromatic/aggdesigner-algorithm/6.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/hydromatic/aggdesigner-algorithm/6.0/aggdesigner-algorithm-6.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/hydromatic/aggdesigner-algorithm/6.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/net/hydromatic/aggdesigner-algorithm/6.0/aggdesigner-algorithm-6.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/hydromatic/aggdesigner/6.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/net/hydromatic/aggdesigner/6.0/aggdesigner-6.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/hydromatic/aggdesigner-algorithm/6.0/aggdesigner-algorithm-6.0.jar
/usr/share/java/.m2/repository/net/hydromatic/aggdesigner-algorithm/6.0/aggdesigner-algorithm-6.0.pom
/usr/share/java/.m2/repository/net/hydromatic/aggdesigner/6.0/aggdesigner-6.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-aggdesigner/LICENSE
/usr/share/package-licenses/mvn-aggdesigner/NOTICE
/usr/share/package-licenses/mvn-aggdesigner/pentaho-aggdesigner-algorithm_LICENSE.txt
/usr/share/package-licenses/mvn-aggdesigner/pentaho-aggdesigner-core_LICENSE.txt
/usr/share/package-licenses/mvn-aggdesigner/pentaho-aggdesigner-ui_LICENSE.txt
